apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::898080060887:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-MpnZCy7m8s1K
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::898080060887:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-25T05:34:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1178"
  uid: 14e41c0f-02a6-4b46-a4d4-047d6aa9e338
